on:
  workflow_dispatch:

jobs:
  web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4